# Generated by Django 3.2.15 on 2022-09-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=250)),
                ('bdesc', models.TextField()),
                ('byear', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
